on: [push]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: Test ktlint install
    steps:
    - uses: actions/checkout@v2
    - id: foo
      uses: nbadal/action-ktlint-setup@v1
      with:
        ktlint_version: 'latest'
    - run: ktlint --version
      shell: bash